version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 890439389777.dkr.ecr.ap-south-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - FRONTEND_REPO=890439389777.dkr.ecr.ap-south-1.amazonaws.com/mean-frontend
      - BACKEND_REPO=890439389777.dkr.ecr.ap-south-1.amazonaws.com/mean-backend

  build:
    commands:
      - echo Building the Docker images...
      - docker build -t $FRONTEND_REPO:$COMMIT_HASH ./client
      - docker build -t $BACKEND_REPO:$COMMIT_HASH ./server

  post_build:
    commands:
      - echo Pushing the Docker images to Amazon ECR...
      - docker push $FRONTEND_REPO:$COMMIT_HASH
      - docker push $BACKEND_REPO:$COMMIT_HASH
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"mean-frontend","imageUri":"%s"},{"name":"mean-backend","imageUri":"%s"}]' $FRONTEND_REPO:$COMMIT_HASH $BACKEND_REPO:$COMMIT_HASH > imagedefinitions.json

aritfacts:
  files:
    - imagedefinitions.json
